name: CI

on:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 11
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'maven'
        
        - name: Test dependency
          run: mvn test
        
        - name: Build with Maven
          run: |
           mvn -B -P github package -file pom.xml
           mkdir staging && cp target/*.jar staging
        
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
           name: Package
           path: staging


    


