name: CD

on:
    push:
     branches:
       - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 11
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'maven'
            server-id: github
            settings-path: ${{ github.workspace }}
        
        - name: Build with Maven
          run: |
           mvn -B -P github package -file pom.xml
         
        - name: Publish to GitHub Packages Apache Maven
          # if: ${{needs.release-please.outputs.release_created}}
          run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
        # - name: upload artifact
        #   uses: actions/upload-artifact@v4
        #   with:
        #    name: Package
        #    path: staging
